name: Test and lint

on:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
          cache: poetry
      - name: Install Python packages
        run: poetry install
      - name: Lint with ruff
        run: poetry run poe lint
      - name: Type checking with mypy
        run: poetry run poe typecheck
      - name: Test with pytest
        run: poetry run poe test
